# .travis.yml
language: python

notifications:
  # will post a summary as comment on githubin case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never

env:
  - LUA="lua=5.1.5"
before_install:
  - sudo ./install-dev.sh

install:
  - pip install openwisp-utils[qa]>=0.3.1

script:
  - openwisp-utils-qa-checks --skip-checkmigrations --skip-isort --skip-flake8
  - ./runtests
